services:

  backend:
    build: .
    container_name: backend
    volumes:
      - ./core:/app
    command: python manage.py runserver 0.0.0.0:80000
    env_file:
      - ./core/.env 
      
  db:
    image: postgres:17
    container_name: postgres
    restart: always
    env_file:
      - ./core/.env
    posrts:
    - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 
