services:

  backend:
    build: .
    container_name: reservation
    volumes:
      - ./core:/app
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./core/.env 
    ports:
      - 8000:8000
      
  