# Generated by Django 5.2 on 2026-09-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationconfigmodel',
            name='day_of_week',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
