# Generated by Django 5.2 on 2026-09-11 20:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservationconfigmodel_day_of_week'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationconfigmodel',
            name='reserved_by',
            field=models.ManyToManyField(blank=True, related_name='user_reserve', to=settings.AUTH_USER_MODEL),
        ),
    ]
