# Generated by Django 5.2 on 2026-09-14 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservationmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationconfigmodel',
            name='reserved_by',
        ),
    ]
