# Generated by Django 5.2 on 2026-09-15 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_remove_reservationconfigmodel_reserved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmodel',
            name='reservation_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_config', to='reservation.reservationconfigmodel'),
        ),
    ]
