# Generated by Django 5.2 on 2026-09-15 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_reservationmodel_reservation_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmodel',
            name='reservation_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservation.reservationconfigmodel'),
        ),
    ]
